package com.regolith.data.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import androidx.room.Upsert
import kotlinx.coroutines.flow.Flow

/*
 * DAOs = typed query interfaces Room implements at compile time.
 * `Flow` return types re-emit whenever the underlying table changes, which
 * is how screens stay live without manual refresh plumbing.
 *
 * Upserts here are hand-rolled (find by natural key, then insert or update)
 * because Room's @Upsert resolves conflicts by primary key, and our natural
 * keys are unique indexes on autogenerated rows.
 */

@Dao
interface ServerDao {
    @Query("SELECT * FROM servers ORDER BY createdAtMs")
    fun observeAll(): Flow<List<ServerEntity>>

    @Query("SELECT * FROM servers WHERE id = :id")
    suspend fun byId(id: Long): ServerEntity?

    @Query("SELECT * FROM servers WHERE id = :id")
    fun byIdBlocking(id: Long): ServerEntity?

    @Query("SELECT * FROM servers WHERE host = :host AND port = :port")
    suspend fun byHost(host: String, port: Int): ServerEntity?

    @Insert
    suspend fun insert(server: ServerEntity): Long

    @Update
    suspend fun update(server: ServerEntity)

    @Query("DELETE FROM servers WHERE id = :id")
    suspend fun delete(id: Long)
}

@Dao
interface ShareDao {
    @Query("SELECT * FROM shares WHERE serverId = :serverId ORDER BY name")
    fun observeForServer(serverId: Long): Flow<List<ShareEntity>>

    @Query("SELECT * FROM shares WHERE enabled = 1 ORDER BY serverId, name")
    fun observeEnabled(): Flow<List<ShareEntity>>

    @Query("SELECT * FROM shares WHERE id = :id")
    suspend fun byId(id: Long): ShareEntity?

    @Query("SELECT * FROM shares WHERE id = :id")
    fun byIdBlocking(id: Long): ShareEntity?

    @Query("SELECT * FROM shares WHERE serverId = :serverId AND name = :name")
    suspend fun byName(serverId: Long, name: String): ShareEntity?

    @Insert
    suspend fun insert(share: ShareEntity): Long

    @Update
    suspend fun update(share: ShareEntity)

    /** Insert new shares, refresh sizes on known ones, keep the user's enabled flags. */
    @Transaction
    suspend fun upsertAll(shares: List<ShareEntity>): List<ShareEntity> = shares.map { incoming ->
        val existing = byName(incoming.serverId, incoming.name)
        if (existing == null) {
            incoming.copy(id = insert(incoming))
        } else {
            existing.copy(freeBytes = incoming.freeBytes, totalBytes = incoming.totalBytes).also { update(it) }
        }
    }

    @Query("UPDATE shares SET enabled = :enabled WHERE id = :id")
    suspend fun setEnabled(id: Long, enabled: Boolean)
}

@Dao
interface FolderDao {
    @Query("SELECT * FROM folders WHERE id = :id")
    suspend fun byId(id: Long): FolderEntity?

    @Query("SELECT * FROM folders WHERE id = :id")
    fun observe(id: Long): Flow<FolderEntity?>

    @Query("SELECT * FROM folders WHERE shareId = :shareId AND relPath = :relPath")
    suspend fun byPath(shareId: Long, relPath: String): FolderEntity?

    @Query("SELECT * FROM folders WHERE parentId = :parentId ORDER BY name COLLATE NOCASE")
    fun observeChildren(parentId: Long): Flow<List<FolderEntity>>

    @Insert
    suspend fun insert(folder: FolderEntity): Long

    @Update
    suspend fun update(folder: FolderEntity)

    @Query("DELETE FROM folders WHERE parentId = :parentId AND relPath NOT IN (:keepPaths)")
    suspend fun deleteChildrenNotIn(parentId: Long, keepPaths: List<String>)

    /** Returns the row for (shareId, relPath), creating it if needed. Ids never change. */
    @Transaction
    suspend fun upsert(folder: FolderEntity): FolderEntity {
        val existing = byPath(folder.shareId, folder.relPath) ?: return folder.copy(id = insert(folder))
        val merged = existing.copy(
            name = folder.name,
            fileCount = folder.fileCount,
            byteCount = folder.byteCount,
            lastListedAtMs = folder.lastListedAtMs ?: existing.lastListedAtMs,
        )
        update(merged)
        return merged
    }
}

@Dao
interface MediaFileDao {
    @Query("SELECT * FROM media_files WHERE id = :id")
    suspend fun byId(id: Long): MediaFileEntity?

    @Query("SELECT * FROM media_files WHERE id = :id")
    fun byIdBlocking(id: Long): MediaFileEntity?

    @Query("SELECT * FROM media_files WHERE shareId = :shareId AND relPath = :relPath")
    suspend fun byPath(shareId: Long, relPath: String): MediaFileEntity?

    @Query("SELECT * FROM media_files WHERE folderId = :folderId AND missing = 0 ORDER BY name COLLATE NOCASE")
    fun observeInFolder(folderId: Long): Flow<List<MediaFileEntity>>

    @Query("SELECT * FROM media_files WHERE folderId = :folderId AND missing = 0 ORDER BY name COLLATE NOCASE")
    suspend fun inFolder(folderId: Long): List<MediaFileEntity>

    @Insert
    suspend fun insert(file: MediaFileEntity): Long

    @Update
    suspend fun update(file: MediaFileEntity)

    @Query("UPDATE media_files SET missing = 1 WHERE folderId = :folderId AND relPath NOT IN (:seenPaths)")
    suspend fun markMissingNotIn(folderId: Long, seenPaths: List<String>)

    /**
     * Insert or refresh by (shareId, relPath). A file that reappears after
     * being marked missing gets its row (and therefore its progress) back.
     */
    @Transaction
    suspend fun upsert(file: MediaFileEntity): MediaFileEntity {
        val existing = byPath(file.shareId, file.relPath) ?: return file.copy(id = insert(file))
        val merged = existing.copy(
            folderId = file.folderId,
            name = file.name,
            ext = file.ext,
            sizeBytes = file.sizeBytes,
            modifiedAtMs = file.modifiedAtMs,
            missing = false,
            lastSeenAtMs = file.lastSeenAtMs,
        )
        update(merged)
        return merged
    }
}

@Dao
interface PlaybackProgressDao {
    @Query("SELECT * FROM playback_progress WHERE fileId = :fileId")
    suspend fun byFile(fileId: Long): PlaybackProgressEntity?

    @Query("SELECT * FROM playback_progress WHERE fileId IN (:fileIds)")
    fun observeForFiles(fileIds: List<Long>): Flow<List<PlaybackProgressEntity>>

    @Upsert
    suspend fun upsert(progress: PlaybackProgressEntity)
}
