package com.regolith.data.db

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import androidx.room.Upsert
import kotlinx.coroutines.flow.Flow

/*
 * DAOs = typed query interfaces Room implements at compile time.
 * `Flow` return types re-emit whenever the underlying table changes, which
 * is how screens stay live without manual refresh plumbing.
 *
 * Upserts here are hand-rolled (find by natural key, then insert or update)
 * because Room's @Upsert resolves conflicts by primary key, and our natural
 * keys are unique indexes on autogenerated rows.
 */

@Dao
interface ServerDao {
    @Query("SELECT * FROM servers ORDER BY createdAtMs")
    fun observeAll(): Flow<List<ServerEntity>>

    @Query("SELECT * FROM servers WHERE id = :id")
    suspend fun byId(id: Long): ServerEntity?

    @Query("SELECT * FROM servers WHERE id = :id")
    fun byIdBlocking(id: Long): ServerEntity?

    @Query("SELECT * FROM servers WHERE host = :host AND port = :port")
    suspend fun byHost(host: String, port: Int): ServerEntity?

    @Insert
    suspend fun insert(server: ServerEntity): Long

    @Update
    suspend fun update(server: ServerEntity)

    @Query("DELETE FROM servers WHERE id = :id")
    suspend fun delete(id: Long)

    /** A listing, scan or transfer got through: the server is back. Also stamps lastSeenAtMs. */
    @Query("UPDATE servers SET unreachableSinceMs = NULL, lastSeenAtMs = :now WHERE id = :id")
    suspend fun markReachable(id: Long, now: Long)

    /** Only the first failure sets the timestamp, so "out of reach since" stays honest. */
    @Query("UPDATE servers SET unreachableSinceMs = COALESCE(unreachableSinceMs, :now) WHERE id = :id")
    suspend fun markUnreachable(id: Long, now: Long)
}

@Dao
interface ShareDao {
    @Query("SELECT * FROM shares WHERE serverId = :serverId ORDER BY name")
    fun observeForServer(serverId: Long): Flow<List<ShareEntity>>

    @Query("SELECT * FROM shares WHERE enabled = 1 ORDER BY serverId, name")
    fun observeEnabled(): Flow<List<ShareEntity>>

    @Query("SELECT * FROM shares WHERE id = :id")
    suspend fun byId(id: Long): ShareEntity?

    @Query("SELECT * FROM shares WHERE id = :id")
    fun byIdBlocking(id: Long): ShareEntity?

    @Query("SELECT * FROM shares WHERE serverId = :serverId AND name = :name")
    suspend fun byName(serverId: Long, name: String): ShareEntity?

    @Insert
    suspend fun insert(share: ShareEntity): Long

    @Update
    suspend fun update(share: ShareEntity)

    /** Insert new shares, refresh sizes on known ones, keep the user's enabled flags. */
    @Transaction
    suspend fun upsertAll(shares: List<ShareEntity>): List<ShareEntity> = shares.map { incoming ->
        val existing = byName(incoming.serverId, incoming.name)
        if (existing == null) {
            incoming.copy(id = insert(incoming))
        } else {
            existing.copy(freeBytes = incoming.freeBytes, totalBytes = incoming.totalBytes).also { update(it) }
        }
    }

    @Query("UPDATE shares SET enabled = :enabled WHERE id = :id")
    suspend fun setEnabled(id: Long, enabled: Boolean)
}

@Dao
interface FolderDao {
    @Query("SELECT * FROM folders WHERE id = :id")
    suspend fun byId(id: Long): FolderEntity?

    @Query("SELECT * FROM folders WHERE id = :id")
    fun observe(id: Long): Flow<FolderEntity?>

    @Query("SELECT * FROM folders WHERE shareId = :shareId AND relPath = :relPath")
    suspend fun byPath(shareId: Long, relPath: String): FolderEntity?

    @Query("SELECT * FROM folders WHERE parentId = :parentId ORDER BY name COLLATE NOCASE")
    fun observeChildren(parentId: Long): Flow<List<FolderEntity>>

    @Insert
    suspend fun insert(folder: FolderEntity): Long

    @Update
    suspend fun update(folder: FolderEntity)

    @Query("DELETE FROM folders WHERE parentId = :parentId AND relPath NOT IN (:keepPaths)")
    suspend fun deleteChildrenNotIn(parentId: Long, keepPaths: List<String>)

    /** Returns the row for (shareId, relPath), creating it if needed. Ids never change. */
    @Transaction
    suspend fun upsert(folder: FolderEntity): FolderEntity {
        val existing = byPath(folder.shareId, folder.relPath) ?: return folder.copy(id = insert(folder))
        // A parent's listing re-upserts its children before they are walked (lastListedAtMs null):
        // that must not wipe the counts the child's own listing wrote earlier.
        val listed = folder.lastListedAtMs != null
        val merged = existing.copy(
            name = folder.name,
            fileCount = if (listed) folder.fileCount else existing.fileCount,
            byteCount = if (listed) folder.byteCount else existing.byteCount,
            lastListedAtMs = folder.lastListedAtMs ?: existing.lastListedAtMs,
            kind = folder.kind ?: existing.kind,
            titleParsed = folder.titleParsed ?: existing.titleParsed,
            year = folder.year ?: existing.year,
        )
        update(merged)
        return merged
    }

    @Query("UPDATE folders SET kind = :kind, titleParsed = :titleParsed, year = :year WHERE id = :id")
    suspend fun setKind(id: Long, kind: String, titleParsed: String?, year: Int?)

    @Query("SELECT * FROM folders WHERE shareId IN (:shareIds) AND parentId IS NULL")
    fun observeRoots(shareIds: List<Long>): Flow<List<FolderEntity>>

    @Query("SELECT * FROM folders WHERE shareId IN (:shareIds) ORDER BY name COLLATE NOCASE")
    fun observeInShares(shareIds: List<Long>): Flow<List<FolderEntity>>

    @Query("SELECT * FROM folders WHERE parentId = :parentId")
    suspend fun children(parentId: Long): List<FolderEntity>

    @Query("SELECT folders.* FROM folders JOIN folder_fts ON folders.id = folder_fts.rowid WHERE folder_fts MATCH :match AND folders.parentId IS NOT NULL LIMIT :limit")
    fun searchFolders(match: String, limit: Int): Flow<List<FolderEntity>>
}

@Dao
interface MediaFileDao {
    @Query("SELECT * FROM media_files WHERE id = :id")
    suspend fun byId(id: Long): MediaFileEntity?

    @Query("SELECT * FROM media_files WHERE id = :id")
    fun observe(id: Long): Flow<MediaFileEntity?>

    @Query("SELECT * FROM media_files WHERE id = :id")
    fun byIdBlocking(id: Long): MediaFileEntity?

    @Query("SELECT * FROM media_files WHERE shareId = :shareId AND relPath = :relPath")
    suspend fun byPath(shareId: Long, relPath: String): MediaFileEntity?

    @Query("SELECT * FROM media_files WHERE folderId = :folderId AND missing = 0 ORDER BY name COLLATE NOCASE")
    fun observeInFolder(folderId: Long): Flow<List<MediaFileEntity>>

    @Query("SELECT * FROM media_files WHERE folderId = :folderId AND missing = 0 ORDER BY name COLLATE NOCASE")
    suspend fun inFolder(folderId: Long): List<MediaFileEntity>

    /**
     * A playback queue's files, in whatever order SQLite returns them; the
     * caller re-orders to match the queue, which is the order you saw on the
     * wall and not one the database knows about.
     */
    @Query("SELECT * FROM media_files WHERE id IN (:ids) AND missing = 0")
    suspend fun byIds(ids: List<Long>): List<MediaFileEntity>

    @Insert
    suspend fun insert(file: MediaFileEntity): Long

    @Update
    suspend fun update(file: MediaFileEntity)

    @Query("UPDATE media_files SET missing = 1 WHERE folderId = :folderId AND relPath NOT IN (:seenPaths)")
    suspend fun markMissingNotIn(folderId: Long, seenPaths: List<String>)

    /** What frame extraction learns in passing; never overwrites a value the full probe set. */
    @Query(
        "UPDATE media_files SET durationMs = COALESCE(durationMs, :durationMs), width = COALESCE(width, :width), height = COALESCE(height, :height) WHERE id = :id",
    )
    suspend fun fillBasics(id: Long, durationMs: Long?, width: Int?, height: Int?)

    /** The full container probe (Title Detail). */
    @Query(
        "UPDATE media_files SET durationMs = COALESCE(:durationMs, durationMs), width = :width, height = :height, frameRate = :frameRate, " +
            "videoCodec = :videoCodec, hdr = :hdr, audioCodec = :audioCodec, audioChannels = :audioChannels, audioSampleRate = :audioSampleRate, probedAtMs = :probedAtMs WHERE id = :id",
    )
    suspend fun saveProbe(
        id: Long,
        durationMs: Long?,
        width: Int?,
        height: Int?,
        frameRate: Float?,
        videoCodec: String?,
        hdr: Boolean?,
        audioCodec: String?,
        audioChannels: Int?,
        audioSampleRate: Int?,
        probedAtMs: Long,
    )

    /**
     * Insert or refresh by (shareId, relPath). A file that reappears after
     * being marked missing gets its row (and therefore its progress) back.
     */
    @Transaction
    suspend fun upsert(file: MediaFileEntity): MediaFileEntity {
        val existing = byPath(file.shareId, file.relPath) ?: return file.copy(id = insert(file))
        val merged = existing.copy(
            folderId = file.folderId,
            name = file.name,
            ext = file.ext,
            sizeBytes = file.sizeBytes,
            modifiedAtMs = file.modifiedAtMs,
            missing = false,
            lastSeenAtMs = file.lastSeenAtMs,
            titleParsed = file.titleParsed ?: existing.titleParsed,
            year = file.year ?: existing.year,
            season = file.season ?: existing.season,
            episode = file.episode ?: existing.episode,
        )
        update(merged)
        return merged
    }

    @Query("SELECT * FROM media_files WHERE folderId IN (:folderIds) AND missing = 0 ORDER BY name COLLATE NOCASE")
    fun observeInFolders(folderIds: List<Long>): Flow<List<MediaFileEntity>>

    @Query("SELECT * FROM media_files WHERE id IN (:ids)")
    fun observeByIds(ids: List<Long>): Flow<List<MediaFileEntity>>

    /** Everything under a share, for Library counts and "files under this collection". */
    @Query("SELECT * FROM media_files WHERE shareId IN (:shareIds) AND missing = 0")
    fun observeInShares(shareIds: List<Long>): Flow<List<MediaFileEntity>>

    @Query("SELECT COUNT(*) FROM media_files WHERE shareId IN (:shareIds) AND missing = 0")
    fun observeCountInShares(shareIds: List<Long>): Flow<Int>

    /** Newest files first (Home's "Newly added"). */
    @Query("SELECT * FROM media_files WHERE missing = 0 ORDER BY addedAtMs DESC, id DESC LIMIT :limit")
    fun observeNewest(limit: Int): Flow<List<MediaFileEntity>>

    /** Files with unfinished progress, most recently watched first (Home's "Continue watching"). */
    @Query(
        "SELECT media_files.* FROM media_files JOIN playback_progress ON playback_progress.fileId = media_files.id " +
            "WHERE media_files.missing = 0 AND playback_progress.completed = 0 AND playback_progress.positionMs > 0 " +
            "ORDER BY playback_progress.updatedAtMs DESC LIMIT :limit",
    )
    fun observeContinueWatching(limit: Int): Flow<List<MediaFileEntity>>

    @Query("SELECT media_files.* FROM media_files JOIN media_fts ON media_files.id = media_fts.rowid WHERE media_fts MATCH :match AND media_files.missing = 0 LIMIT :limit")
    fun search(match: String, limit: Int): Flow<List<MediaFileEntity>>
}

@Dao
interface ScanRunDao {
    @Insert
    suspend fun insert(run: ScanRunEntity): Long

    @Update
    suspend fun update(run: ScanRunEntity)

    @Query("SELECT * FROM scan_runs WHERE id = :id")
    suspend fun byId(id: Long): ScanRunEntity?

    /** The latest run per share, for every share given. */
    @Query("SELECT * FROM scan_runs WHERE id IN (SELECT MAX(id) FROM scan_runs WHERE shareId IN (:shareIds) GROUP BY shareId)")
    fun observeLatest(shareIds: List<Long>): Flow<List<ScanRunEntity>>

    @Query("SELECT * FROM scan_runs WHERE status = 'RUNNING'")
    fun observeRunning(): Flow<List<ScanRunEntity>>

    /** A process that died mid-scan leaves RUNNING rows behind; WorkManager restarts the work, so mark them. */
    @Query("UPDATE scan_runs SET status = 'CANCELLED', finishedAtMs = :now WHERE status = 'RUNNING'")
    suspend fun cancelAllRunning(now: Long)
}

@Dao
interface RecentSearchDao {
    @Query("SELECT * FROM recent_searches ORDER BY searchedAtMs DESC LIMIT :limit")
    fun observeRecent(limit: Int): Flow<List<RecentSearchEntity>>

    @Upsert
    suspend fun upsert(entry: RecentSearchEntity)

    @Query("DELETE FROM recent_searches")
    suspend fun clear()
}

@Dao
interface PlaybackProgressDao {
    @Query("SELECT * FROM playback_progress WHERE fileId = :fileId")
    suspend fun byFile(fileId: Long): PlaybackProgressEntity?

    @Query("SELECT * FROM playback_progress WHERE fileId IN (:fileIds)")
    fun observeForFiles(fileIds: List<Long>): Flow<List<PlaybackProgressEntity>>

    @Upsert
    suspend fun upsert(progress: PlaybackProgressEntity)
}

@Dao
interface ArtworkDao {
    @Query("SELECT * FROM artwork WHERE ownerType = :ownerType AND ownerId = :ownerId AND kind = :kind")
    suspend fun get(ownerType: String, ownerId: Long, kind: String): ArtworkEntity?

    @Query("SELECT * FROM artwork WHERE ownerType = :ownerType AND ownerId = :ownerId AND kind = :kind")
    fun observe(ownerType: String, ownerId: Long, kind: String): Flow<ArtworkEntity?>

    @Insert
    suspend fun insert(artwork: ArtworkEntity): Long

    @Update
    suspend fun update(artwork: ArtworkEntity)

    /** Replace by (ownerType, ownerId, kind); the row id is not meaningful to anyone. */
    @Transaction
    suspend fun upsert(artwork: ArtworkEntity): ArtworkEntity {
        val existing = get(artwork.ownerType, artwork.ownerId, artwork.kind) ?: return artwork.copy(id = insert(artwork))
        val merged = artwork.copy(id = existing.id)
        update(merged)
        return merged
    }

    @Query("SELECT COUNT(*) FROM artwork WHERE source != 'PLACEHOLDER'")
    fun observeCount(): Flow<Int>

    /** Rows the app made itself, as opposed to an image found on the share. */
    @Query("SELECT * FROM artwork WHERE source IN ('FRAMEGRAB', 'MOSAIC', 'PLACEHOLDER')")
    suspend fun generated(): List<ArtworkEntity>

    @Query("DELETE FROM artwork WHERE source IN ('FRAMEGRAB', 'MOSAIC', 'PLACEHOLDER')")
    suspend fun deleteGenerated()

    /** Drops a folder's mosaic so the next request re-runs the source order and finds the new sidecar. */
    @Query("DELETE FROM artwork WHERE ownerType = :ownerType AND ownerId = :ownerId AND source = 'MOSAIC'")
    suspend fun deleteMosaic(ownerType: String, ownerId: Long)

    @Query("DELETE FROM artwork")
    suspend fun deleteAll()
}

@Dao
interface TransferDao {
    @Query("SELECT * FROM transfers ORDER BY createdAtMs DESC")
    fun observeAll(): Flow<List<TransferEntity>>

    @Query("SELECT * FROM transfers WHERE fileId = :fileId")
    fun observeForFile(fileId: Long): Flow<TransferEntity?>

    @Query("SELECT * FROM transfers WHERE fileId = :fileId")
    suspend fun byFile(fileId: Long): TransferEntity?

    @Query("SELECT * FROM transfers WHERE fileId = :fileId AND status = 'DONE'")
    fun doneForFileBlocking(fileId: Long): TransferEntity?

    @Query("SELECT * FROM transfers WHERE fileId = :fileId AND status = 'DONE'")
    suspend fun doneForFile(fileId: Long): TransferEntity?

    @Query("SELECT * FROM transfers WHERE status = :status")
    suspend fun allWith(status: String): List<TransferEntity>

    @Insert
    suspend fun insert(transfer: TransferEntity): Long

    @Update
    suspend fun update(transfer: TransferEntity)

    @Query("DELETE FROM transfers WHERE fileId = :fileId")
    suspend fun deleteForFile(fileId: Long)

    @Query("DELETE FROM transfers WHERE status = 'FAILED'")
    suspend fun deleteFailed()

    /** Rows a dead process left RUNNING; WorkManager re-runs the work, so they become QUEUED. */
    @Query("UPDATE transfers SET status = 'QUEUED' WHERE status = 'RUNNING'")
    suspend fun requeueRunning()
}
